name: 自动打包插件

on:
  push:
    branches:
      - main  # 触发打包的分支，可以根据需要修改
  pull_request:
    branches:
      - main  # 可以修改为触发的 PR 分支

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v3

      - name: 打包插件
        run: |
          bash pack_plugin.sh

      - name: 上传插件
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: |
            MoreGameEvents-*.mcdr